### ISSUE TITLE
select cell and the cell moves to left a bit 

### ISSUE THREAD

**Issue by athemer** [superpeteblaze/ScalingCarousel#13] opened 2017-08-22 15:24 UTC
hi, 
when I select the cells, it scrolls a little bit to the left.
also, for example, if I have a tab bar vc as parent and two child vc.
I add the collectionView to child A, the same situation happens when I switch back from vc B.
Is this fixable ?
thanks !

**Comment by StPayne55** [comment] 2017-09-17 13:46
I'm having the same issue. When selecting a cell, I perform a push segue. After unwinding back to the collection view screen, the cells overlap and sometimes the last cell is scaled to around 1.5 it's normal size.

**Comment by jshrager** [comment] 2017-09-17 16:28
Yeh I'm having same issue - glad someone else has. I've added two screenshots. When I first load it works fine, but when i tap a cell and open another view controller and then close that view controller it goes horribly wrong!
<img width="621" alt="screen shot 2017-09-17 at 17 27 11" src="https://user-images.githubusercontent.com/811976/30522769-967f5f06-9bcd-11e7-9480-d12dd5aa307e.png">
<img width="620" alt="screen shot 2017-09-17 at 17 27 22" src="https://user-images.githubusercontent.com/811976/30522770-96a006f2-9bcd-11e7-99bb-41d74b56e0d7.png">

**Comment by superpeteblaze** [comment] 2017-09-17 18:27
Thanks for the screenshots @jshrager, I'll look in to this.

**Comment by jshrager** [comment] 2017-09-23 07:31
Not sure if you've found / replicated issue yet - but i have app on my iPhone 7 Plus running iOS 11 and not seen the issue yet - but when i put it on my wife's iPhone 6s 10.3 originally this is how i saw the issue.

**Comment by superpeteblaze** [comment] 2017-09-25 08:02
Thanks for update @jshrager, I have reproduced in the sample app in this repo, and aim to get a fix in as soon as I can.

**Comment by cnbuff410** [comment] 2017-11-22 19:18
I'm running into a similar issue, but not completely the same. For me I put the carousel inside a ScrollView, every time when I do "pull to refresh" all the cards become to be same size and make the screen very crowded, similar to what @jshrager shows here.

Any known solution for this?

**Comment by superpeteblaze** [comment] 2017-11-23 10:08
I have not had time to look in to this yet. If you get a chance to investigate, maybe you could propose a solution and open a PR.

**Comment by kingsofteng** [comment] 2017-12-09 03:16
Hey guys, That's happening because of not connecting scrollview delegate.
Hi @superpeteblaze , Just add description to connect ScalingCarouselView's delegate to container view controller so that "scrollViewDidScroll" delegate function can be called exactly.
You mentioned only about connecting DataSource in the Usage section.
Hope it will help you guys.
Thanks.

**Comment by superpeteblaze** [comment] 2017-12-10 14:46
Thanks @kingsofteng. The readme states that you need to set the collection delegate. Does this solve you issue @athemer  @StPayne55 @cnbuff410 @jshrager ? If so, I will close this.

**Comment by cnbuff410** [comment] 2017-12-16 00:27
I have both `data source` and `delegate`set to my main view controller if it is what you mean.

**Comment by cnbuff410** [comment] 2018-01-30 04:25
I just manually call "didScroll()" every time the screen show up on the phone, and that solve the issue for me temporarily.

**Comment by superpeteblaze** [comment] 2018-01-30 08:59
Ok, thanks for the feedback @cnbuff410 . I will try to find a long-term solution when I get the time.

**Comment by edurd** [comment] 2018-02-06 17:41
How did you manage to add shadow to the cell?

**Comment by tolikvasylyk** [comment] 2018-02-09 16:33
Interesting me too, because the shadow is clipped if I try to add it. Did you add it like another view on the sides of MainView?

**Comment by pabsanmez** [comment] 2018-05-26 23:19
@athemer did you solve it?,

When I tap on a cell it goes to the left and again to the right.

**Comment by superpeteblaze** [comment] 2018-05-28 02:13
Thanks @pabsanmez for pointing out the correct solution 👍🏼

**Closed by superpeteblaze** 2018-05-28 02:13 UTC
Labels: bug
