### ISSUE TITLE
Initializing the carousel by showing the second or later item results in wrong scaling

### ISSUE THREAD

**Issue by mwawrusch** [superpeteblaze/ScalingCarousel#41] opened 2018-06-11 13:54 UTC
When initializing the view (in viewDidLoad)
```
        scalingCarousel!.scrollToItem(at: IndexPath(row: 1, section: 0), at: .centeredHorizontally, animated: false)
        scalingCarousel!.deviceRotated()
```
the right item scalng gets messed up. It works fine when I scroll to  element 0 though:

![img_c176ed739e19-1](https://user-images.githubusercontent.com/481276/41207148-6557abf8-6cc5-11e8-8c3f-f4c5f07a308c.jpeg)

**Comment by superpeteblaze** [comment] 2018-06-12 05:52
Thanks for opening this @mwawrusch 👍🏼

**Comment by bijuC1983** [comment] 2018-08-09 12:08
Hello @superpeteblaze .. I am faced with the same issue.. Was there a possible fix for this?

**Comment by superpeteblaze** [comment] 2018-08-09 18:13
No, this issue has not yet been resolved @bijuC1983.

**Comment by bijuC1983** [comment] 2018-08-10 03:49
For now this solved it for me
` func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as! ScalingCarouselCell
        DispatchQueue.main.async {
            cell.setNeedsLayout()
            cell.layoutIfNeeded()
            if indexPath.row == 0 && !self.scrollSet {
                let originX = (CGFloat(self.currIndex) * (self.carouselView.frame.size.width - (self.carouselView.inset * 2)))
                let rect = CGRect(x: originX, y: 0, width: self.carouselView.frame.size.width - (self.carouselView.inset * 2), height: self.carouselView.frame.height)
                self.carouselView.scrollRectToVisible(rect, animated: false)
                self.carouselView.didScroll()
                self.scrollSet = true
            }
        }
        
        return cell
    }`

**Comment by superpeteblaze** [comment] 2018-08-10 13:58
Thanks for coming back with this @bijuC1983. Do you think this is something that could be added to ScalingCarousel directly? If so, It would be great to open a PR for it

**Comment by alibozoglu** [comment] 2018-11-01 00:48
`scalingCarousel!.scrollToItem(at: IndexPath(row: 1, section: 0), at: .centeredHorizontally, animated: false)`
`scalingCarousel.reloadItems(at: [IndexPath.init(row: index, section: 0)])`

**Comment by superpeteblaze** [comment] 2020-05-10 11:05
Closing as could not reproduce.

**Closed by superpeteblaze** 2020-05-10 11:05 UTC
Labels: bug
